# Service Accounts for AI-Driven Detection Engineering Platform
# Version: 1.0
# Security Controls:
# - Automatic token rotation (24h period)
# - RBAC with namespace isolation
# - Detailed audit logging (90-day retention)
# - Enforced mountable secrets
# - SOC2 and GDPR compliant

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
  labels:
    app: detection-platform
    component: backend
    security-tier: restricted
    environment: ${ENV}
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    security.platform.io/token-rotation: "enabled"
    security.platform.io/audit-logging: "detailed"
    security.platform.io/token-ttl: "86400"  # 24 hours in seconds
    security.platform.io/audit-retention: "90d"
    security.platform.io/compliance: "soc2,gdpr"
automountServiceAccountToken: true
secrets:
  - name: backend-secrets

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-service-account
  labels:
    app: detection-platform
    component: monitoring
    security-tier: restricted
    environment: ${ENV}
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    monitoring.platform.io/metrics-scraping: "enabled"
    security.platform.io/audit-logging: "detailed"
    security.platform.io/token-ttl: "86400"  # 24 hours in seconds
    security.platform.io/audit-retention: "90d"
    security.platform.io/compliance: "soc2,gdpr"
automountServiceAccountToken: true
secrets:
  - name: monitoring-secrets

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-service-account
  labels:
    app: detection-platform
    component: worker
    security-tier: restricted
    environment: ${ENV}
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    security.platform.io/token-rotation: "enabled"
    security.platform.io/audit-logging: "detailed"
    security.platform.io/token-ttl: "86400"  # 24 hours in seconds
    security.platform.io/audit-retention: "90d"
    security.platform.io/compliance: "soc2,gdpr"
automountServiceAccountToken: true
secrets:
  - name: backend-secrets