apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: detection-platform-monitoring
  labels:
    app: loki
    component: logging
data:
  loki.yaml: |
    auth_enabled: true  # Enable authentication for production security

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
      http_server_read_timeout: 30s
      http_server_write_timeout: 30s
      grpc_server_max_recv_msg_size: 104857600  # 100MB
      grpc_server_max_send_msg_size: 104857600  # 100MB

    common:
      path_prefix: /data
      storage:
        filesystem:
          chunks_directory: /data/chunks
          rules_directory: /data/rules
      replication_factor: 3  # HA with 3 replicas
      ring:
        kvstore:
          store: memberlist  # Use memberlist for HA clustering
        heartbeat_timeout: 1m
        
    memberlist:
      join_members:
        - loki-headless.detection-platform-monitoring.svc.cluster.local:7946
      
    schema_config:
      configs:
        - from: "2023-01-01"
          store: boltdb-shipper
          object_store: filesystem
          schema: v12
          index:
            prefix: index_
            period: 24h
            
    ruler:
      alertmanager_url: http://alertmanager.detection-platform-monitoring.svc.cluster.local:9093
      enable_api: true
      enable_alertmanager_v2: true
      ring:
        kvstore:
          store: memberlist
      rule_path: /data/rules
      storage:
        type: local
        local:
          directory: /data/rules
      evaluation_interval: 1m
      poll_interval: 1m
      
    limits_config:
      retention_period: 744h  # 31 days retention
      enforce_metric_name: false
      max_entries_limit_per_query: 5000
      reject_old_samples: true
      reject_old_samples_max_age: 168h  # 7 days
      creation_grace_period: 1h
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_global_streams_per_user: 5000
      max_query_length: 721h  # 30 days + 1h buffer
      max_query_parallelism: 32
      cardinality_limit: 100000  # Prevent cardinality explosions
      
    chunk_store_config:
      max_look_back_period: 744h  # Match retention period
      chunk_cache_config:
        enable_fifocache: true
        fifocache:
          max_size_bytes: 1073741824  # 1GB chunk cache
          validity: 24h
          
    table_manager:
      retention_deletes_enabled: true
      retention_period: 744h
      poll_interval: 24h
      
    compactor:
      working_directory: /data/compactor
      shared_store: filesystem
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      
    query_scheduler:
      max_outstanding_requests_per_tenant: 100
      
    frontend:
      compress_responses: true
      log_queries_longer_than: 10s
      downstream_url: http://loki-querier.detection-platform-monitoring.svc.cluster.local:3100
      
    query_range:
      split_queries_by_interval: 24h
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_bytes: 536870912  # 512MB
            validity: 1h
            
    analytics:
      reporting_enabled: false  # Disable usage reporting for security