# Version: v1.0.0
# Purpose: Grafana configuration for AI-Driven Detection Engineering platform monitoring
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: detection-platform-monitoring
  labels:
    app: grafana
    component: monitoring
    part-of: detection-platform
data:
  # Main Grafana configuration file
  grafana.ini: |
    [server]
    protocol = http
    http_port = 3000
    domain = grafana.detection-platform.internal
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    serve_from_sub_path = true
    read_timeout = 30s
    write_timeout = 30s
    enable_gzip = true
    cert_file = /etc/grafana/certs/tls.crt
    cert_key = /etc/grafana/certs/tls.key

    [security]
    # Enhanced security settings
    admin_user = admin
    allow_embedding = true
    cookie_secure = true
    cookie_samesite = strict
    disable_gravatar = true
    strict_transport_security = true
    strict_transport_security_max_age_seconds = 31536000
    content_security_policy = true
    content_security_policy_template = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"
    x_content_type_options = true
    x_xss_protection = true

    [auth]
    # Authentication configuration
    disable_login_form = false
    disable_signout_menu = false
    oauth_auto_login = false
    signout_redirect_url = ""
    login_maximum_inactive_lifetime_duration = 7d
    login_maximum_lifetime_duration = 30d
    token_rotation_interval_minutes = 60

    [users]
    # User management settings
    allow_sign_up = false
    auto_assign_org = true
    auto_assign_org_role = Editor
    default_theme = dark
    viewers_can_edit = false
    editors_can_admin = false

    [auth.proxy]
    enabled = false
    header_name = X-WEBAUTH-USER
    header_property = username
    auto_sign_up = false

    [metrics]
    # Metrics collection settings
    enabled = true
    basic_auth_username = metrics
    interval_seconds = 10
    disable_total_stats = false

    [dashboards]
    # Dashboard configuration
    versions_to_keep = 20
    min_refresh_interval = 5s
    default_home_dashboard_path = /var/lib/grafana/dashboards/platform-overview.json

    [alerting]
    # Alerting configuration
    enabled = true
    execute_alerts = true
    evaluation_timeout_seconds = 30
    notification_timeout_seconds = 30
    max_attempts = 3

    [unified_alerting]
    enabled = true
    execute_alerts = true
    evaluation_timeout = 30s
    max_attempts = 3

    [panels]
    # Panel settings
    disable_sanitize_html = false
    enable_alpha = false

    [feature_toggles]
    enable = publicDashboards

  # Data source configuration
  datasources.yaml: |
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        version: 1
        editable: false
        jsonData:
          timeInterval: "15s"
          queryTimeout: "30s"
          httpMethod: "POST"
          manageAlerts: true
          alertmanagerUid: "alertmanager"
          prometheusType: "Prometheus"
          prometheusVersion: "2.45.0"
          exemplarTraceIdDestinations:
            - name: trace_id
              datasourceUid: jaeger
        secureJsonData:
          httpHeaderValue1: "Bearer ${PROMETHEUS_TOKEN}"

      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          maxLines: 1000
          timeout: 30
          derivedFields:
            - name: trace_id
              matcherRegex: "trace_id=(\\w+)"
              url: "$${__value.raw}"
              datasourceUid: jaeger

      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger-query:16686
        jsonData:
          nodeGraph:
            enabled: true

  # Dashboard provider configuration
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'Detection Platform'
        orgId: 1
        folder: 'Detection Platform'
        type: file
        disableDeletion: true
        updateIntervalSeconds: 30
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true

  # Default home dashboard configuration
  platform-overview.json: |
    {
      "title": "Platform Overview",
      "tags": ["overview", "detection-platform"],
      "timezone": "browser",
      "refresh": "1m",
      "panels": [
        {
          "title": "API Response Times",
          "type": "graph",
          "gridPos": {"x": 0, "y": 0, "w": 12, "h": 8},
          "targets": [
            {
              "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
              "legendFormat": "95th Percentile"
            }
          ],
          "thresholds": [
            {
              "value": 0.5,
              "colorMode": "critical",
              "op": "gt",
              "fill": true,
              "line": true
            }
          ]
        },
        {
          "title": "System Uptime",
          "type": "stat",
          "gridPos": {"x": 12, "y": 0, "w": 6, "h": 4},
          "targets": [
            {
              "expr": "avg_over_time(up[30d]) * 100",
              "legendFormat": "Uptime %"
            }
          ],
          "thresholds": {
            "steps": [
              { "value": 99.9, "color": "green" },
              { "value": 99.5, "color": "yellow" },
              { "value": 99.0, "color": "red" }
            ]
          }
        }
      ]
    }