version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Use builder stage for development
      args:
        NODE_ENV: development
        VITE_API_BASE_URL: http://localhost:8000
        VITE_WS_BASE_URL: ws://localhost:8000/ws
        VITE_DEBUG_LEVEL: verbose
        VITE_ENABLE_DEV_TOOLS: "true"
        BUILD_VERSION: 1.0.0
    ports:
      - "3000:80"  # Main application port
      - "9229:9229"  # Node.js debugging port
    volumes:
      # Source code mounting for hot reload
      - type: bind
        source: .
        target: /app
        consistency: cached
      # Persistent node_modules volume
      - type: volume
        source: node_modules
        target: /app/node_modules
      # PNPM store for optimized package management
      - type: volume
        source: pnpm-store
        target: /app/.pnpm-store
    environment:
      - NODE_ENV=development
      - VITE_APP_NAME=AI Detection Platform
      - VITE_APP_VERSION=1.0.0
      - VITE_APP_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_WS_BASE_URL=ws://localhost:8000/ws
      - VITE_ENABLE_ANALYTICS=false
      - VITE_ENABLE_SENTRY=false
      - VITE_DEBUG_LEVEL=verbose
      - VITE_ENABLE_DEV_TOOLS=true
      - VITE_HOT_RELOAD=true
      - VITE_SOURCEMAP=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - detection-platform
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2g
        reservations:
          cpus: '0.5'
          memory: 1g

networks:
  detection-platform:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: detection-net
      com.docker.network.bridge.enable_icc: "true"

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: /docker/volumes/node_modules
      o: bind
  pnpm-store:
    driver: local
    driver_opts:
      type: none
      device: /docker/volumes/pnpm-store
      o: bind